### ISSUE TITLE
'--overrides' instead of '--limits'

### ISSUE THREAD

**Issue by KayFaessler** [Gradiant/ettus-device-plugin#3]
Since '--limits' doesn't work anymore one should use '--overrides'. So in order to test a pod with the daemonset, the following command should be used:

`kubectl run test-usrp -ti --rm --privileged --image openverso/ettus-uhd --override-type=strategic --overrides='{"spec":{"containers":[{"name":"test-usrp","resources":{"limits":{"ettus.com/usrp":"1"}}}]}}' -- benchmark_rate --rx_rate 10e6 --tx_rate 10e6`

**Comment by cgiraldo** [comment]
README.md updated. 

Thanks for your apport!
